<?php


class Circle extends Shapes implements iResizable
{
    private $diameter;

    public function __construct($name, $diameter)
    {
        parent::__construct($name); // TODO: Change the autogenerated stub
        $this->diameter=$diameter;
    }

    public function CalculateArea()
    {
        // TODO: Implement CalculateArea() method.
        $area = (pi())*(($this->diameter)/2)*(($this->diameter)/2);
        return $area;
    }

    public function Resize($areachange)
    {
        $area = $this->CalculateArea();
        $finalarea = $area * (($areachange)/100);
        $diameter = sqrt($finalarea/(pi()))*2;
        $this->diameter = $diameter;
        return $finalarea;
    }

    public function getdia()
    {
        return $this->diameter;
    }
}