<?php


class Rectangle extends Shapes
{
    private $length;
    private $width;

    public function __construct($name, $length, $width)
    {
        parent::__construct($name); // TODO: Change the autogenerated stub
        $this->length = $length;
        $this->width = $width;
    }

    public function CalculateArea()
    {
        // TODO: Implement CalculateArea() method.
        $area = $this->length*$this->width;
        return $area;
    }
}