<?php


class Triangle extends Shapes implements iResizable
{
    private $base;
    private $height;

    public function __construct($name, $base, $height)
    {
        parent::__construct($name); // TODO: Change the autogenerated stub
        $this->base = $base;
        $this->height = $height;
    }

    public function CalculateArea()
    {
        // TODO: Implement CalculateArea() method.
        $area = (1/2)*$this->base*$this->height;
        return $area;
    }

    public function Resize($areachange)
    {
        $area = $this->CalculateArea();
        $finalarea = $area * (($areachange)/100);
        $height = (2*$finalarea)/$this->base;
        $this->height = $height;
        return $finalarea;
    }

    public function getheight()
    {
        return $this->height;
    }
}