CREATE DATABASE CarsDB;
GO

USE CarsDB;
GO

CREATE TABLE CARS_CAR_TYPES
(CAR_TYPE     VARCHAR(15));

INSERT INTO CARS_CAR_TYPES VALUES ('FORD');
INSERT INTO CARS_CAR_TYPES VALUES ('TOYOTA');
INSERT INTO CARS_CAR_TYPES VALUES ('VOLKSWAGEN');
INSERT INTO CARS_CAR_TYPES VALUES ('CHEVY');


CREATE TABLE CARS_NUMBER_OF_DOORS
(DOORS   int);

INSERT INTO CARS_NUMBER_OF_DOORS VALUES (2);
INSERT INTO CARS_NUMBER_OF_DOORS VALUES (4);

CREATE TABLE CARS_COLORS
(COLOR     VARCHAR(15));

INSERT INTO CARS_COLORS VALUES ('WHITE');
INSERT INTO CARS_COLORS VALUES ('RED');
INSERT INTO CARS_COLORS VALUES ('GREEN');