CREATE DATABASE  NumbersDB;
GO

USE NumbersDB;
GO

DROP TABLE IF EXISTS NUMBERS_0_TO_9;
DROP TABLE IF EXISTS NUMBERS_TWOS;
DROP TABLE IF EXISTS NUMBERS_THREES;
DROP TABLE IF EXISTS NUMBERS_FIVES;

-- CREATE THE NUMBERS_0_TO_9 TABLE
CREATE TABLE NUMBERS_0_TO_9
(DIGIT    int);

INSERT INTO NUMBERS_0_TO_9 VALUES (0);
INSERT INTO NUMBERS_0_TO_9 VALUES (1);
INSERT INTO NUMBERS_0_TO_9 VALUES (2);
INSERT INTO NUMBERS_0_TO_9 VALUES (3);
INSERT INTO NUMBERS_0_TO_9 VALUES (4);
INSERT INTO NUMBERS_0_TO_9 VALUES (5);
INSERT INTO NUMBERS_0_TO_9 VALUES (6);
INSERT INTO NUMBERS_0_TO_9 VALUES (7);
INSERT INTO NUMBERS_0_TO_9 VALUES (8);
INSERT INTO NUMBERS_0_TO_9 VALUES (9);
GO

-- CREATE THE NUMBERS_0_TO_99 VIEW
CREATE VIEW NUMBERS_0_TO_99 AS
SELECT (A.DIGIT * 10) + B.DIGIT AS N
FROM NUMBERS_0_TO_9 A,
     NUMBERS_0_TO_9 B;
GO

CREATE TABLE NUMBERS_TWOS
(MULTIPLE_OF_2      int);

INSERT INTO NUMBERS_TWOS 
SELECT n * 2
FROM NUMBERS_0_TO_99
WHERE N BETWEEN 0 AND 50;

CREATE TABLE NUMBERS_THREES
(MULTIPLE_OF_3      int);

INSERT INTO NUMBERS_THREES 
SELECT n * 3
FROM NUMBERS_0_TO_99
WHERE N BETWEEN 0 AND 33;

CREATE TABLE NUMBERS_FIVES
(MULTIPLE_OF_5      int);

INSERT INTO NUMBERS_FIVES 
SELECT n * 5
FROM NUMBERS_0_TO_99
WHERE N BETWEEN 0 AND 20;