# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Study Material\Programming\w0411567-MajumderE\Tax_Calculation_With_Gui\Tax_Calculation_with_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelasksalary = QtWidgets.QLabel(self.centralwidget)
        self.labelasksalary.setGeometry(QtCore.QRect(160, 80, 141, 31))
        self.labelasksalary.setObjectName("labelasksalary")
        self.lineEditsalaryInput = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditsalaryInput.setGeometry(QtCore.QRect(350, 80, 113, 31))
        self.lineEditsalaryInput.setObjectName("lineEditsalaryInput")
        self.labelaskdependent = QtWidgets.QLabel(self.centralwidget)
        self.labelaskdependent.setGeometry(QtCore.QRect(160, 120, 191, 31))
        self.labelaskdependent.setObjectName("labelaskdependent")
        self.lineEditnumberofDependent = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditnumberofDependent.setGeometry(QtCore.QRect(350, 120, 113, 31))
        self.lineEditnumberofDependent.setObjectName("lineEditnumberofDependent")
        self.pushButtoncalculateTax = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtoncalculateTax.setGeometry(QtCore.QRect(270, 180, 75, 23))
        self.pushButtoncalculateTax.setObjectName("pushButtoncalculateTax")
        self.FrameShowDetails = QtWidgets.QFrame(self.centralwidget)
        self.FrameShowDetails.setGeometry(QtCore.QRect(160, 210, 301, 171))
        self.FrameShowDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameShowDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameShowDetails.setObjectName("FrameShowDetails")
        self.labelptaxwithheld = QtWidgets.QLabel(self.FrameShowDetails)
        self.labelptaxwithheld.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.labelptaxwithheld.setObjectName("labelptaxwithheld")
        self.labelftaxwithheld = QtWidgets.QLabel(self.FrameShowDetails)
        self.labelftaxwithheld.setGeometry(QtCore.QRect(10, 50, 161, 16))
        self.labelftaxwithheld.setObjectName("labelftaxwithheld")
        self.labeltwithheld = QtWidgets.QLabel(self.FrameShowDetails)
        self.labeltwithheld.setGeometry(QtCore.QRect(10, 110, 161, 16))
        self.labeltwithheld.setObjectName("labeltwithheld")
        self.labelthomepay = QtWidgets.QLabel(self.FrameShowDetails)
        self.labelthomepay.setGeometry(QtCore.QRect(10, 140, 161, 16))
        self.labelthomepay.setObjectName("labelthomepay")
        self.labeldependentdeduction = QtWidgets.QLabel(self.FrameShowDetails)
        self.labeldependentdeduction.setGeometry(QtCore.QRect(10, 80, 191, 16))
        self.labeldependentdeduction.setObjectName("labeldependentdeduction")
        self.labelprovincialTax = QtWidgets.QLabel(self.FrameShowDetails)
        self.labelprovincialTax.setGeometry(QtCore.QRect(230, 20, 47, 13))
        self.labelprovincialTax.setObjectName("labelprovincialTax")
        self.labelfederalTax = QtWidgets.QLabel(self.FrameShowDetails)
        self.labelfederalTax.setGeometry(QtCore.QRect(230, 50, 47, 13))
        self.labelfederalTax.setObjectName("labelfederalTax")
        self.labeldeductionforDependent = QtWidgets.QLabel(self.FrameShowDetails)
        self.labeldeductionforDependent.setGeometry(QtCore.QRect(230, 80, 47, 13))
        self.labeldeductionforDependent.setObjectName("labeldeductionforDependent")
        self.labeltotalWithheld = QtWidgets.QLabel(self.FrameShowDetails)
        self.labeltotalWithheld.setGeometry(QtCore.QRect(230, 110, 47, 13))
        self.labeltotalWithheld.setObjectName("labeltotalWithheld")
        self.labeltakeHomepay = QtWidgets.QLabel(self.FrameShowDetails)
        self.labeltakeHomepay.setGeometry(QtCore.QRect(230, 140, 47, 13))
        self.labeltakeHomepay.setObjectName("labeltakeHomepay")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(210, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tax Calculator"))
        self.labelasksalary.setText(_translate("MainWindow", "What is your weekly salary?:"))
        self.labelaskdependent.setText(_translate("MainWindow", "How many dependents do you have?:"))
        self.pushButtoncalculateTax.setText(_translate("MainWindow", "Calculate Tax"))
        self.labelptaxwithheld.setText(_translate("MainWindow", "Provincial Tax Withheld:"))
        self.labelftaxwithheld.setText(_translate("MainWindow", "Federal Tax Withheld:"))
        self.labeltwithheld.setText(_translate("MainWindow", "Total Withheld:"))
        self.labelthomepay.setText(_translate("MainWindow", "Total Take HomePay:"))
        self.labeldependentdeduction.setText(_translate("MainWindow", "Dependent deduction"))
        self.labelprovincialTax.setText(_translate("MainWindow", "TextLabel"))
        self.labelfederalTax.setText(_translate("MainWindow", "TextLabel"))
        self.labeldeductionforDependent.setText(_translate("MainWindow", "TextLabel"))
        self.labeltotalWithheld.setText(_translate("MainWindow", "TextLabel"))
        self.labeltakeHomepay.setText(_translate("MainWindow", "TextLabel"))
        self.labelName.setText(_translate("MainWindow", "Tax Calculator"))

